### ISSUE TITLE
Passing OAuth access_token to upstream via Authorisation header (rather than X-Forwarded-Access-Token)

### ISSUE THREAD

**Issue by k-wall** [openshift/oauth-proxy#107]
In our use-case, we want to use oauth-proxy to protect a user-facing application (HTML/JS single page app).

oauth-proxy will be used to allow the user to authenticate against the OpenShift OAuth server, serve the application's static content, and provide a proxy to an API server.   The user's interactions with the application will cause API calls to be made.   The application won't be in possession of the access_token, so I wanted to rely on oauth-proxy to argument the authenticated request with the authentication user's access token as it traversed the oauth-proxy.

I have found `--pass-access-token=true` which does almost what I want, however the API server in question does not understand X-Forwarded-Access-Token.  I desire a version of the `--pass-access-token` option that would pass OAuth access_token of the authenticated user to upstream via Authorisation header formatted in the bearer format..

I can't change the API server to understand X-Forwarded-Access-Token (the API server in question is the Kubernetes API server itself).

Is there another way to use oauth-proxy that would achieve the same ends?  Alternatively, I would be happy to submit a PR.

Thanks in advance.

**Comment by InfoSec812** [comment]
I'm in the same situation. I thought that `--pass-user-bearer-token=true` would solve this, but I am getting odd results. For example, my config looks like:

```
        containers:
        - name: oauth-proxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: ${{PROXY_PORT}}
            protocol: TCP
          args:
          - "--https-address="
          - "--http-address=:${PROXY_PORT}"
          - "--provider=openshift"
          - "--openshift-service-account=proxy"
          - "--upstream=https://openshift.default.svc:443/oapi"
          - "--upstream=https://openshift.default.svc:443/api"
          - "--upstream=http://localhost:${APP_PORT}"
          - '--cookie-name=OCP_TOKEN'
          - '--cookie-expire=24h0m0s'
          - '--cookie-refresh=8h0m0s'
          - "--cookie-domain=.rht-labs.com"
          - "--cookie-name=OCP_TOKEN"
          - "--cookie-secret=${COOKIE_SECRET}"
          - "--pass-user-bearer-token=true"
```

But when my front-end makes a request through the proxy for `/oapi/v1` I get an NGinx 404 page from the UI server instead of a response from the OpenShift API.
