### ISSUE TITLE
Not able to connect to the container

### ISSUE THREAD

**Issue by Bashayr29** [openshift/oauth-proxy#131]
Since the container listens only on localhost, I want to access the container inside the pod (that use oauth-proxy) from another pod. How to access it? I was trying to use service name and the port `curl service:port` of container but it doesn't work 
```
Failed to connect to 1x.xx.x.xx port xxxx: Connection refused
* Closing connection 0
```

**Comment by mrogers950** [comment]
Normally you just use a service. There could be something wrong with your service configuration.
See https://github.com/openshift/oauth-proxy/blob/master/contrib/sidecar.yaml#L23 for a simple example.

**Comment by Bashayr29** [comment]
@mrogers950 my service configuration seems good:
```
 - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: https
        service.alpha.openshift.io/serving-cert-secret-name: prom-tls
      labels:
        name: prom
      name: prom
    spec:
      ports:
        - name: prometheus
          port: 443
          protocol: TCP
          targetPort: 8443
      selector:
        app: prom
```
