### ISSUE TITLE
Authentication error when trying to run through OAuth Proxy with GitHub IdP

### ISSUE THREAD

**Issue by meiaus** [openshift/oauth-proxy#144]
On OCP 4.2, I configure OAuth Proxy as sidecar and GitHub as IdP for user login.
GitHub Oauth application's `Authorization callback URL` is set as:
`https://oauth-openshift.apps.meloids.os.fyre.ibm.com/oauth2callback/github_provider`

When attempting to start running my application via proxy URL, e.g. `https://acme-proxy-acmetest.apps.meloids.os.fyre.ibm.com/AcmeAnnuityWeb`, 
- first `login with open shift` displayed:
![image](https://user-images.githubusercontent.com/27024803/70257834-b7669f80-1750-11ea-9564-5dc8a88d0532.png)

- after selecting the login, next URL `https://oauth-openshift.apps.meloids.os.fyre.ibm.com/oauth/authorize?approval_prompt=force&client_id=system%3Aserviceaccount%3Aacmetest%3Aacmesa&redirect_uri=https%3A%2F%2Facme-proxy-acmetest.apps.meloids.os.fyre.ibm.com%2Foauth%2Fcallback&response_type=code&scope=user%3Ainfo+user%3Acheck-access&state=289df4c7871763b54779babbbbc47faf%3A%2FAcmeAnnuityWeb' displayed with the provider list:

![image](https://user-images.githubusercontent.com/27024803/70257964-fa287780-1750-11ea-883c-68007d90640c.png)

- after selecting 'github_provider', the github login page displayed with URL `https://github.com/login?client_id=71d151a386cebf140a37&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3D71d151a386cebf140a37%26redirect_uri%3Dhttps%253A%252F%252Foauth-openshift.apps.meloids.os.fyre.ibm.com%252Foauth2callback%252Fgithub_provider%26response_type%3Dcode%26scope%3Duser%253Aemail%2Bread%253Aorg%26state%3DY3NyZj1oZGtP ....`

![image](https://user-images.githubusercontent.com/27024803/70258145-4d022f00-1751-11ea-9fa7-2ee6e432b14f.png)

- after logging with github user, next with 2-factor verify page displayed `https://github.com/sessions/two-factor` 
![image](https://user-images.githubusercontent.com/27024803/70258216-6d31ee00-1751-11ea-8dfe-c302a7c36e2a.png)

- after 'verify', the URL is changed to `https://github.com/login/oauth/authorize?client_id=71d151a386cebf140a37&redirect_uri=https%3A%2F%2Foauth-openshift.apps.meloids.os.fyre.ibm.com%2Foauth2callback%2Fgithub_provider&response_type=code&scope=user%3Aemail+read%3Aorg&state=Y3NyZj1pWXFVa0VG ...`

and immediately changed again to `https://oauth-openshift.apps.meloids.os.fyre.ibm.com/oauth2callback/github_provider?code=95b3409d95fca7760157&state=Y3NyZj1oZGtPUmEzZ ...` with authentication error.

![image](https://user-images.githubusercontent.com/27024803/70258433-dca7dd80-1751-11ea-88d4-dd37dfd11b98.png)

- when browser developer tools is turned on, see `404`

![image](https://user-images.githubusercontent.com/27024803/70259594-14b02000-1754-11ea-85df-1cef79ed90da.png)

Please advise what could be the cause of the issue, for example missing any configuration?  Thanks in advance.

Snippet of OAuth proxy yaml:
```
...
        - resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          name: oauth-proxy
          ports:
            - name: 7443-proxy
              containerPort: 7443
              protocol: TCP
          image: 'quay.io/openshift/origin-oauth-proxy:4.1'
          imagePullPolicy: IfNotPresent
          args:
            - '-provider=openshift'
            - >-
              -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
            - '-cookie-secure=true'
            - '-pass-access-token=true'
            - '-cookie-secret=TLP2jUFIqFGNAZxEekbTp51OCxEiGDYfEpLPVLZfbgd'
            - '-https-address=:7443'
            - '-http-address='
            - '-email-domain=*'
            - '-upstream=http://localhost:9081'
            - '-tls-cert=/etc/tls/private/tls.crt'
            - '-tls-key=/etc/tls/private/tls.key'
            - '-openshift-service-account=acmesa'
            - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '-skip-auth-regex=^/metrics'
          volumeMounts:
            - name: secret-acme-tls
              mountPath: /etc/tls/private
...

```
and GitHub IdP:
```
. . .
apiVersion: config.openshift.io/v1
kind: OAuth
. . .
spec:
  identityProviders:
    - github:
        clientID: 71d151a386cebf140a37
        clientSecret:
          name: githubsecret
        . . .
      mappingMethod: claim
      name: github_provider
      type: GitHub
```
