### ISSUE TITLE
[question] What does "workflow: openshift-e2e-aws" mean and how can I run "ci/prow/e2e-aws" in my local environment?

### ISSUE THREAD

**Issue by xkwangcn** [openshift/oauth-proxy#178]
Hi, 
I want to run "ci/prow/e2e-aws" in my local openshift 4.3 environment, but I didn't find its scripts or how to run it? and from here https://github.com/openshift/release/blob/master/ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-release-4.3.yaml, I see the test contents is 
```
tests:
- as: e2e-aws
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
```
do you know where is the workflow `openshift-e2e-aws`? and how can I run it?

In addition, is the workflow `openshift-e2e-aws` here the same as `ci/prow/e2e-aws`?

My goal is to complete the openshft4 test content of oauth-proxy in my local environment.
