### ISSUE TITLE
Authentication by ServiceAccount's Token  

### ISSUE THREAD

**Issue by yeplaa** [openshift/oauth-proxy#179]
Hello,

On Openshift 4, i use a sidecar oauth-proxy v2.3 (docker image ose-oauth-proxy:v4.4.0-202004261927)  in front of Grafana container. Currently i use this configuration for access by GUI, it's works.  But i would access to Grafana by API and it's KO : 

    token=`oc sa get-token  grafana`
    curl -s -o /dev/null -w "%{http_code}" -k -H   "Authorization: Bearer ${token}" https://<grafana_route>
    403

In my statefulset, bellow the oauth configuration : 

            args:
            - -provider=openshift
            - -https-address=:8443
            - -http-address=
            - -email-domain=*
            - -upstream=http://localhost:3000
            - -client-id=system:serviceaccount:${PROJECT_NAME}:grafana
            - -openshift-service-account=grafana
            - -openshift-ca=/etc/root-ca.crt
            - -openshift-ca=/etc/intermediate.crt
            - -openshift-ca=/etc/pki/tls/cert.pem
            - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - '-openshift-sar={"resource": "namespaces", "verb": "get", "resourceName": "$(PROJECT_NAME)", "namespace": "$(PROJECT_NAME)"}'
            - -tls-cert=/etc/tls/private/tls.crt
            - -tls-key=/etc/tls/private/tls.key
            - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
            - -cookie-secret-file=/etc/proxy/secrets/session_secret
            - -skip-auth-regex=^/metrics 

I try to add a '-openshift-delegate-urls={"/": {"resource": "projects", "verb": "list"}}' configuration but it's mandatory to have a cluster rights et in my use case, it's not possible. 
I add 'openshift-service-account=grafana' but it's KO also. 

My Serviceaccount Configuration :

       kind: ServiceAccount
       apiVersion: v1
       metadata:
        name: grafana
        annotations:
          serviceaccounts.openshift.io/oauth-redirectreference.first:'{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'

My Service Configuration :
```
- kind: Service
  apiVersion: v1
  metadata:
    name: grafana
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: grafana-proxy-tls
  spec:
    ports:
      - name: grafana
        port: 443
        protocol: TCP
        targetPort: 8443
    selector:
      app: grafana
```
My route configuration : 

```
- kind: Route
  apiVersion: v1
  metadata:
    name: grafana
  spec:
    tls:
      termination: Reencrypt
      insecureEdgeTerminationPolicy: Redirect
    to:
      name: grafana
```

Have you an idea regarding a missing configuration? 

Thanks
Loïc

**Comment by dbluxo** [comment]
I have the same question. I would like to authorize OpenShift service accounts or infrastructure components to specific APIs through the oauth-proxy. I can only get it to work if I use `-openshift-delegate-urls`, but this requires cluster admin rights. Is there another option?

**Comment by yeplaa** [comment]
With Admin user, It seems necessary to add rights of system:auth-delegator clusterrole to my serviceaccount. Then it works with `--openshift-delegate-urls` . But currently, i don't know what are the impacts in terms of security if every users have this rights ?

**Comment by dbluxo** [comment]
I am also looking for a way to solve it without admin rights.

**Comment by chrisob** [comment]
Not sure if this is quite what you're looking for, but this repo contains an example Grafana deployment which uses the oauth-proxy to auth end-users: https://github.com/chrisob/openshift-user-workload-monitoring-grafana

**Comment by HumairAK** [comment]
Would also be interested in knowing a way around requiring `openshift-delegate-urls` to authenticate service-accounts that does not require cluster scope privileges! :)

**Comment by gerardcl** [comment]
hi @yeplaa , can you share how  values on your flags `--openshift-delegate-urls` and `--openshift-sar` look like on your working config? thanks in advance!

**Comment by dastrobu** [comment]
I think have the same issue here. To me it looks like if the oauth proxy always tries to do a `SubjectAccessReview` instead of a `LocalSubjectAccessReview`. So when running the oauth proxy with permissions limited to the current namespace this is an issue and one finds in the logs:
```
main.go:138: Invalid configuration:
--
  | unable to load OpenShift configuration: unable to retrieve authentication information for tokens: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:my-namespace:oauth-proxy" cannot create tokenreviews.authentication.k8s.io at the cluster scope: no RBAC policy matched
```
config is:
```
--openshift-delegate-urls={"namespace":"my-namespace","resource":"namespaces","name":"my-namespace","verb":"get"}
```

if comparing this to the `openshift-sar` config, where specifying a namespace results in a `LocalSubjectAccessReview`
```
--openshift-sar={"namespace":"my-namespace", "resource": {"namespace":"my-namespace","resource":"namespaces","name":"my-namespace","verb":"get"}}
```
I don't see how to make the delegation be based on `LocalSubjectAccessReview`. 

Probably I got something wrong, but if this is the issue, fixing it would be really helpful.

**Comment by anishasthana** [comment]
It seemed like the only way to get oauth-proxy working as a side-car was by giving it cluster reader. Being able to restrict the permissions to a single namespace would be very helpful.

**Comment by stlaz** [comment]
Eh, cluster-reader is way way too broad, please, don't do that. `system:auth-delegator` should suffice.

The proxy uses SARs because those allow the checks to generically check any kind of permissions in the cluster and you are less likely to shoot yourself in the leg with it compared to LSARs.

**Comment by dastrobu** [comment]
unfortunately as a normal admin of a namespace we don't have the option to use `system:auth-delegator`. 
When trying to assign this role I receive 
```
Reason: rolebindings is forbidden: attempt to grant extra privileges: [{[create] [authentication.k8s.io] [tokenreviews] [] []} {[create] [authorization.k8s.io] [subjectaccessreviews] [] []} ...
```

So a solution that relies on normal namespace scoped privileges would be really helpful. Not sure how I can do this without LSARs.

**Comment by IlonkaO** [comment]
Same here!
OpenShift 4.6.17 and ose-grafana v4.6

**Comment by dastrobu** [comment]
After looking a bit into the code, my understanding is that it is actually not the issue with `SubjectAccessReview` vs `LocalSubjectAccessReview`. The log states 
```
unable to load OpenShift configuration: unable to retrieve authentication information for tokens: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:my-namespace:oauth-proxy" cannot create tokenreviews.authentication.k8s.io at the cluster scope: no RBAC policy matched
```
Which means its failing on the `TokenAccessReview` before even attempting to do a `SubjectAccessReview` or `LocalSubjectAccessReview`. 
This means, the authentication https://github.com/openshift/oauth-proxy/blob/8b627c351c350a4992245c11fb677d5a4618efe1/providers/openshift/provider.go#L323 step fails before doing the authorization step in https://github.com/openshift/oauth-proxy/blob/8b627c351c350a4992245c11fb677d5a4618efe1/providers/openshift/provider.go#L343. 

Getting permission for a `TokenAccessReview` is not possible as well in our cluster setup. 

My though to get around all these issues would be:

Replace the authentication and authorization step with a simple `SelfSubjectRulesReview` when receiving a Bearer token. Wouldn't that make sense? I would at least circumvent all the RBAC issues with normal namespace permissions and it should result in the same authorization check in the end. Maybe I am missing something here. I would like to hear your thoughts.

**Comment by ssgdevops** [comment]
Hello, I would like to reopen this one. 
I’m using the grafana-operator which use the oauth-proxy toward my openshift cluster.
I’m using :
```yaml
 oc get clusterversion                                                                                                                  
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.9.11    True        False         37d     Cluster version is 4.9.11
```

And i’m getting this logs from the oauth-proxy:
```
~ » oc logs grafana-deployment-769685f8d9-6n789 grafana-proxy                                                                              
2022/02/16 15:04:52 provider.go:117: Defaulting client-id to system:serviceaccount:grafana:grafana-serviceaccount
2022/02/16 15:04:52 provider.go:122: Defaulting client-secret to service account token /var/run/secrets/kubernetes.io/serviceaccount/token
2022/02/16 15:04:52 provider.go:310: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
2022/02/16 15:04:52 main.go:138: Invalid configuration:
  unable to load OpenShift configuration: unable to retrieve authentication information for tokens: the server could not find the requested resource
----
```

I tried to lookup after it as I was able to get it working on an 4.7 Cluster version. I did check the differences between the two (without getting on the cluster deep ) and they are the same.

Where should I start ?

Thanks,

**Comment by gerardcl** [comment]
hi all, I second what @ssgdevops reported, and  I want to add that I also got it working on openshift dedicated 4.8, but not working (same error) in OCP4.9.

**Comment by stlaz** [comment]
> Which means its failing on the TokenAccessReview before even attempting to do a SubjectAccessReview or LocalSubjectAccessReview.

If it's not possible to tell who is trying to log in, it does not matter to check whether they are authorized because you don't know who they were in the first place.

**Comment by stlaz** [comment]
/close
Authentication with SA tokens is not supposed to work with this proxy.

The logs from https://github.com/openshift/oauth-proxy/issues/179#issuecomment-1041594447 show that the SA does not have required privileges.

**Comment by arve0** [comment]
> The logs from https://github.com/openshift/oauth-proxy/issues/179#issuecomment-1041594447 show that the SA does not have required privileges.

Sure about that @stlaz?

I tried with and without role _system:auth-delegator_, without a ClusterRoleBinding to system:auth-delegator the error message is:

>  unable to load OpenShift configuration: unable to retrieve authentication information for tokens: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:default:proxy" cannot create resource "tokenreviews" in API group "authentication.k8s.io" at the cluster scope

With a ClusterRoleBinding to system:auth-delegator the error message is:

>  unable to load OpenShift configuration: unable to retrieve authentication information for tokens: the server could not find the requested resource

YAML to reproduce:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy
  namespace: default
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"proxy"}}'
# Create a secure connection to the proxy via a route
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-can-create-token-reviews
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: proxy
  namespace: default
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: proxy
  namespace: default
spec:
  to:
    kind: Service
    name: proxy
  tls:
    termination: Reencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: proxy-tls
spec:
  ports:
  - name: proxy
    port: 443
    targetPort: 8443
  selector:
    app: proxy
# Launch a proxy as a sidecar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy
      containers:
      - name: oauth-proxy
        image: openshift/oauth-proxy:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        ports:
        - containerPort: 8443
          name: public
        args:
        - --https-address=:8443
        - --provider=openshift
        - --openshift-service-account=proxy
        - --upstream=http://localhost:8080
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - '--openshift-delegate-urls={"/":{"group":"","resource":"pods","verb":"get"}}'
        - --cookie-secret=SECRET
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls

      - name: app
        image: openshift/hello-openshift:latest
      volumes:
      - name: proxy-tls
        secret:
          secretName: proxy-tls
```

Server version:
```
Server Version: 4.9.37
Kubernetes Version: v1.22.8+f34b40c
```

**Comment by stlaz** [comment]
Quite sure, yes.

You can see that in the first case w/o the clusterrole you're getting the error message telling you that RBAC does not allow you to perform a certain action.
In the second case, with the clusterrole, the error message goes past the RBAC admission and tells you that tokenreviews are not possible due to missing resource. I would dare to assume that you're using an outdated oauth-proxy image that attempts to do v1beta1 TokenReviews which will be no longer available in kube 1.22.

**Comment by arve0** [comment]
> I would dare to assume that you're using an outdated oauth-proxy image that attempts to do v1beta1 TokenReviews which will be no longer available in kube 1.22.

You are correct: https://hub.docker.com/r/openshift/oauth-proxy.

Do you want a PR to update the contrib example? https://github.com/openshift/oauth-proxy/blob/master/contrib/sidecar.yaml#L53

**Comment by arve0** [comment]
With image registry.redhat.io/openshift4/ose-oauth-proxy I am still not able to authenticate as a service account:

```sh
oc run curl-oauth-proxy -n default --rm -i --restart=Never \
                                          --image=registry.redhat.io/openshift4/ose-cli \
                                          --overrides='{"spec":{"serviceAccount":"pipeline"}}' -- \
                                            bash -cx 'oc whoami; oc auth can-i get pods; curl --silent --fail --insecure -H "authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://proxy.default/'
```

Result
```
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: unable to upgrade connection: container curl-oauth-proxy not found in pod curl-oauth-proxy_default
+ oc whoami
system:serviceaccount:default:pipeline
+ oc auth can-i get pods
yes
++ cat /var/run/secrets/kubernetes.io/serviceaccount/token
+ curl --silent --fail --insecure -H 'authorization: Bearer eyJhbGciOiJSUzI1N...' https://proxy.default/
pod "curl-oauth-proxy" deleted
pod default/curl-oauth-proxy terminated (Error)
```

It does work with my own token:
```sh
❯ curl --fail --insecure -H "authorization: Bearer $(oc whoami --show-token)" https://proxy-default.apps.ocp-lab1.regsys.brreg.no/
Hello OpenShift!
```

Delegate argument is:
```
--openshift-delegate-urls={"/":{"groups":"","resource":"pods","verb":"get"}}
```

**Comment by stlaz** [comment]
`- '--openshift-delegate-urls={"/":{"group":"","resource":"pods","verb":"get"}}'` is unbounded to a NS, can your SA `get pods` anywhere?

**Comment by arve0** [comment]
> - '--openshift-delegate-urls={"/":{"group":"","resource":"pods","verb":"get"}}' is unbounded to any NS

Aha.

> can your SA get pods anywhere?

No. Only his own namespace. Is it possible to bind `--openshift-delegate-urls` to "service accounts own namespace"?

What I'm trying to do is getting same behavior for service accounts as registered users. As I understand it, any registered user gets access as default. How would you give all service accounts access?

I guess granting access to a cluster wide resource would work, but it is tedious making sure all service accounts has that cluster wide access.

**Comment by arve0** [comment]
OK, so I made it work by using the group `system:authenticated`. To anyone interested, the complete example is:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-service-account-access
  namespace: default
data:
  description: Fake ConfigMap to give all authenticated users access to a given service behind openshift-oauth-proxy.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth-service-account-access
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  resourceNames:
  - oauth-service-account-access
---
# allow all service accounts read access to configmap oauth-service-account-access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth-service-account-access
  namespace: default
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: oauth-service-account-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy
  namespace: default
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"proxy"}}'
# Create a secure connection to the proxy via a route
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-can-create-token-reviews
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: proxy
  namespace: default
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: proxy
  namespace: default
spec:
  to:
    kind: Service
    name: proxy
  tls:
    termination: Reencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: proxy-tls
spec:
  ports:
  - name: proxy
    port: 443
    targetPort: 8443
  selector:
    app: proxy
# Launch a proxy as a sidecar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy
      containers:
      - name: oauth-proxy
        image: registry.redhat.io/openshift4/ose-oauth-proxy
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        ports:
        - containerPort: 8443
          name: public
        args:
        - --https-address=:8443
        - --provider=openshift
        - --openshift-service-account=proxy
        - --upstream=http://localhost:8080
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --openshift-delegate-urls={"/":{"group":"","resource":"configmaps","verb":"get","namespace":"default","name":"oauth-service-account-access"}}
        - --cookie-secret=SECRET
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls

      - name: app
        image: openshift/hello-openshift:latest
      volumes:
      - name: proxy-tls
        secret:
          secretName: proxy-tls
```

Then one can verify with:

```sh
oc run curl-oauth-proxy -n default --rm -i --restart=Never \
  --image=registry.redhat.io/openshift4/ose-cli -- \
  bash -cx 'oc whoami; oc auth can-i get configmaps/oauth-service-account-access --namespace default; curl --silent --fail --insecure -H "authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://proxy.default/'
```
