### ISSUE TITLE
Inject custom headers

### ISSUE THREAD

**Issue by fabry00** [openshift/oauth-proxy#253]
Hi

is it possible to inject custom headers to the upstream?
My use case is this: I need to inject a Service Account token as Authorization Barer token to the upstream. Then the upstream server will forward the token to thanos for authentication. 

This is my current configuration

```yaml
image: openshift4/ose-oauth-proxy:v4.8'
args:
  - '--https-address=:8443'
  - '--provider=openshift'
  - '--openshift-service-account={{ .Values.service_account }}'
  - '--upstream=http://localhost:{{ .Values.ports.ui }}'
  - '--tls-cert=/etc/tls/private/tls.crt'
  - '--tls-key=/etc/tls/private/tls.key'
  - '--cookie-secret=cookie-secret'
  - '--skip-provider-button'
  - '--pass-basic-auth=false'
```

I would like to do something like this:

```yaml
args:
 - '--upstream=http://localhost:{{ .Values.ports.ui }}'
 - - '--upstream-headers=Authorization: Bearer ${mytocken_from_env_variable}'
```

Thank you
