### ISSUE TITLE
`HTTP 301` redirection responses mangle `Location` header

### ISSUE THREAD

**Issue by andrewazores** [openshift/oauth-proxy#272]
If I make a request to the proxy with a request URI containing encoded path segments, such as `GET /api/foo%2Fbar/baz`, I would expect the proxy to pass that request verbatim to the upstream service (assuming the client passes authz), or to return a redirection response with the `Location` header also set to that same verbatim request URI, potentially with segments removed as needed for proxying to different upstreams by path prefix.

Instead, what I observe is that the proxy sends a 301 redirection response with the `Location` header mangled - the URI has been decoded, so my request to `GET /api/foo%2Fbar/baz` is modified into a request to `GET /api/foo/bar/baz`. The client issues this request as instructed by the proxy, and the upstream service can no longer understand this request.

```
$ http -v --auth=user:pass :4180/api/v1/targets/$(echo -n service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi | jq -sRr @uri)/recordings
GET /api/v1/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Flocalhost%3A0%2Fjmxrmi/recordings HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Authorization: Basic dXNlcjpwYXNz
Connection: keep-alive
Host: localhost:4180
User-Agent: HTTPie/3.2.2



HTTP/1.1 301 Moved Permanently
Content-Length: 107
Content-Type: text/html; charset=utf-8
Date: Fri, 22 Dec 2023 19:19:54 GMT
Gap-Auth: user
Location: /api/v1/targets/service:jmx:rmi:/jndi/rmi:/localhost:0/jmxrmi/recordings

<a href="/api/v1/targets/service:jmx:rmi:/jndi/rmi:/localhost:0/jmxrmi/recordings">Moved Permanently</a>.
```

The `oauth2-proxy` had a similar bug: https://github.com/oauth2-proxy/oauth2-proxy/issues/844 . Unfortunately it looks like that report and the fix came in much later than the point where these two projects diverged, so the codebase is substantially different and the patch cannot be easily backported.

**Comment by andrewazores** [comment]
Here's a simple reproducer in the form of k8s yamls:

```yaml
apiVersion: v1
data:
  htpasswd: dXNlcjokMnkkMDUkLnAxLzY4b0JXS1gxRmhBdFpPQXJZT29Ob01xc0I0eXVVTlhHT2VTQVRIUHEzZ2VLcUVhWlMK
kind: Secret
metadata:
  creationTimestamp: "2023-12-21T20:00:28Z"
  name: basic-auth
  namespace: oauth-proxy
  resourceVersion: "2296"
  uid: e2fad076-09bb-4777-847d-f76502a6375e
type: Opaque
```

----

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - image: quay.io/andrewazores/loggerserver:latest
        imagePullPolicy: Always
        name: loggerserver
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --upstream=http://localhost:4000
        - --cookie-secret=SECRET
        - --openshift-service-account=default
        - --https-address=
        - --htpasswd-file=/etc/htpasswd/htpasswd
        image: quay.io/openshift/origin-oauth-proxy:latest
        imagePullPolicy: Always
        name: origin-oauth-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/htpasswd
          name: htpasswd
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: htpasswd
        secret:
          defaultMode: 420
          secretName: basic-auth
```

----

```bash
$ kubectl create -f ./basic-auth.secret.yaml ./proxy.deployment.yaml
$ kubectl expose deployment proxy
$ oc expose svc proxy` or `kubectl port-forward svc/proxy 4180
$ http :4180` , `http http://user:pass@localhost:4180
```
