### ISSUE TITLE
openshift-delegate-urls does not work as expected

### ISSUE THREAD

**Issue by sreber84** [openshift/oauth-proxy#85]
Running `oauth-proxy` from https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/oauth-proxy/images/latest seems to misbehave when using `openshift-delegate-urls` as access is denied.

Configuration looks as following:
```
[foo@master-1 ~]$ oc project test
Already on project "test" on server "https://openshift.example.com:443".
[foo@master-1 ~]$ oc get svc nodejs
NAME      CLUSTER-IP     EXTERNAL-IP   PORT(S)            AGE
nodejs    172.30.126.6   <none>        443/TCP,8778/TCP   4d
[foo@master-1 ~]$ oc get clusterrolebinding cluster-readers
NAME              ROLE              USERS     GROUPS                   SERVICE ACCOUNTS                                                                        SUBJECTS
cluster-readers   /cluster-reader   simon     system:cluster-readers   management-infra/management-admin, default/router, logging/aggregated-logging-fluentd

[foo@master-1 ~]$ oc whoami
simon

[foo@master-0 ~]$ oc export dc/nodejs
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    app: nodejs
    deploymentconfig: nodejs
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs
        deploymentconfig: nodejs
    spec:
      containers:
      - image: 172.30.138.227:5000/test/nodejs@sha256:281d3b11486581d439294f194e22112d063002b37c199ddcac061140964b30bc
        imagePullPolicy: IfNotPresent
        name: nodejs
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --https-address=:8443
        - --provider=openshift
        - --openshift-service-account=nodejs
        - --upstream=http://localhost:8080
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --validate-url=https://openshift.default.svc.cluster.local/oapi/v1/users/~
        - --redeem-url=https://openshift.default.svc.cluster.local/oauth/token
        - --openshift-review-url=https://openshift.default.svc.cluster.local/oapi/v1/subjectaccessreviews
        - --openshift-delegate-urls={"/":{"resource":"service","verb":"get","namespace":"test","name":"nodejs"}}
        - --cookie-secret-file=/etc/proxy/secrets/session_secret
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: registry.access.redhat.com/openshift3/oauth-proxy@sha256:f3cf64678f5a593d312e0efe4073d9e19313007ed35d1688a3320b6245baaedc
        imagePullPolicy: IfNotPresent
        name: node-oauth-proxy
        ports:
        - containerPort: 8443
          name: public
          protocol: TCP
        resources:
          limits:
            cpu: 5m
            memory: 35Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls
        - mountPath: /etc/proxy/secrets
          name: proxy-secret
        - mountPath: /etc/proxy/htpasswd
          name: prometheus-proxy-htpasswd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nodejs
      serviceAccountName: nodejs
      terminationGracePeriodSeconds: 30
      volumes:
      - name: proxy-tls
        secret:
          defaultMode: 420
          secretName: application-tls
      - name: proxy-secret
        secret:
          defaultMode: 420
          secretName: application-proxy
      - configMap:
          defaultMode: 420
          name: oauth-proxy-htpasswd
        name: prometheus-proxy-htpasswd
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - nodejs
      from:
        kind: ImageStreamTag
        name: nodejs:latest
        namespace: test
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - node-oauth-proxy
      from:
        kind: ImageStreamTag
        name: oauth-proxy:latest
        namespace: test
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

When running the below `curl` command it would actually fail.
```
[quicklab@master-1 ~]$ curl -v -X GET -H "Authorization: Bearer <token>" -k https://nodejs-test.apps.example.com | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to nodejs-test.apps.example.com port 443 (#0)
*   Trying 10.1.1.106...
* Connected to nodejs-test.apps.example.com (10.1.1.106) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=router.default.svc
* 	start date: Aug 24 14:46:04 2018 GMT
* 	expire date: Aug 23 14:46:05 2020 GMT
* 	common name: router.default.svc
* 	issuer: CN=openshift-service-serving-signer@1535118586
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: nodejs-test.apps.example.com
> Accept: */*
> Authorization: Bearer <token>
> HTTP/1.1 403 Forbidden
< Set-Cookie: _oauth_proxy=; Path=/; Domain=nodejs-test.apps.example.com; Expires=Fri, 31 Aug 2018 14:40:43 GMT; HttpOnly; Secure
< Date: Fri, 31 Aug 2018 15:40:43 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
```

`oauth-proxy` would report the following error.

`2018/08/31 15:40:43 provider.go:382: authorizer reason: User "simon" cannot get service in project "test"`

If the user `simon` as `cluster-admin` it works.

Red Hat OpenShift Container Platform version
```
[foo@master-0 ~]$ oc version
oc v3.6.173.0.128
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.example.com:443
openshift v3.6.173.0.128
kubernetes v1.6.1+5115d708d7
```

Checking logs on Red Hat OpenShift Container Platform - Master does not reveal any detail (with default log-level)
